
export const INITIAL_SETUP_SQL = `
-- 1. Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  description text,
  image_url text,
  category text,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Categories Table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  customer_name text,
  customer_email text,
  total_amount numeric,
  status text default 'pending',
  ai_note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MIGRATION: Add user_id if it does not exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'orders' and column_name = 'user_id') then
    alter table public.orders add column user_id uuid references auth.users(id);
  end if;
end $$;

-- 4. Order Items
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_name text,
  price numeric,
  quantity integer,
  image_url text
);

-- 6. Enable RLS (Core Tables)
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- 7. Policies (Core Tables)

-- Products
drop policy if exists "Public Access Products" on public.products;
create policy "Public Access Products" on public.products for select using (true);

drop policy if exists "Public Insert Products" on public.products;
create policy "Public Insert Products" on public.products for insert with check (true);

drop policy if exists "Public Update Products" on public.products;
create policy "Public Update Products" on public.products for update using (true);

drop policy if exists "Public Delete Products" on public.products;
create policy "Public Delete Products" on public.products for delete using (true);

-- Categories
drop policy if exists "Public Access Categories" on public.categories;
create policy "Public Access Categories" on public.categories for select using (true);

drop policy if exists "Public Insert Categories" on public.categories;
create policy "Public Insert Categories" on public.categories for insert with check (true);

drop policy if exists "Public Update Categories" on public.categories;
create policy "Public Update Categories" on public.categories for update using (true);

drop policy if exists "Public Delete Categories" on public.categories;
create policy "Public Delete Categories" on public.categories for delete using (true);

-- Orders
drop policy if exists "Public Access Orders" on public.orders;
create policy "Public Access Orders" on public.orders for select using (true);

drop policy if exists "Public Insert Orders" on public.orders;
create policy "Public Insert Orders" on public.orders for insert with check (true);

-- Order Items
drop policy if exists "Public Access Items" on public.order_items;
create policy "Public Access Items" on public.order_items for select using (true);

drop policy if exists "Public Insert Items" on public.order_items;
create policy "Public Insert Items" on public.order_items for insert with check (true);

-- 8. Storage Buckets
insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict (id) do nothing;

drop policy if exists "Public Storage Select" on storage.objects;
create policy "Public Storage Select" on storage.objects for select using ( bucket_id in ('product-images', 'avatars') );

drop policy if exists "Public Storage Insert" on storage.objects;
create policy "Public Storage Insert" on storage.objects for insert with check ( bucket_id in ('product-images', 'avatars') );
`;
