
export const INVENTORY_ADVANCED_SQL = `
-- 7. Inventory Advanced Features

-- Add SKU column to products if it doesn't exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'sku') then
    alter table public.products add column sku text;
    create index if not exists idx_products_sku on public.products(sku);
  end if;
end $$;

-- Add STOCK column to products if it doesn't exist (Safety check)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'stock') then
    alter table public.products add column stock integer default 0;
  end if;
end $$;

-- Create Inventory Logs Table
create table if not exists public.inventory_logs (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  previous_stock integer,
  new_stock integer,
  change_amount integer,
  reason text, -- 'sale', 'restock', 'adjustment', 'damage', 'return'
  note text,
  user_id uuid, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Logs
alter table public.inventory_logs enable row level security;

-- Policies for Logs
drop policy if exists "Public view logs" on public.inventory_logs;
create policy "Public view logs" on public.inventory_logs for select using (true);

drop policy if exists "Public insert logs" on public.inventory_logs;
create policy "Public insert logs" on public.inventory_logs for insert with check (true);

-- No update policy created means updates are denied by default to preserve audit trail.

drop policy if exists "Admins delete logs" on public.inventory_logs;
create policy "Admins delete logs" on public.inventory_logs for delete using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);
`;
