export const MEDIA_MANAGER_SQL = `
-- 8. Media Manager (v2 - Unified & Idempotent)

-- Create the table with all columns if it doesn't exist
create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  file_name text not null,
  file_path text not null, -- Path in storage bucket
  public_url text not null,
  mime_type text not null,
  size bigint not null, -- size in bytes
  alt_text text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  width integer,
  height integer,
  tags text[],
  updated_at timestamp with time zone
);

-- Add columns for users who might have the old version of the table
alter table public.media_assets add column if not exists width integer;
alter table public.media_assets add column if not exists height integer;
alter table public.media_assets add column if not exists tags text[];
alter table public.media_assets add column if not exists updated_at timestamp with time zone;

-- Indexes for performance
create index if not exists idx_media_assets_mime_type on public.media_assets(mime_type);
create index if not exists idx_media_assets_file_name on public.media_assets(file_name);

-- Enable RLS
alter table public.media_assets enable row level security;

-- Policies (Permissive for Demo UI)
drop policy if exists "Public can manage media assets" on public.media_assets;
create policy "Public can manage media assets" on public.media_assets for all using (true) with check (true);

-- Ensure storage buckets exist (idempotent)
insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict (id) do nothing;

-- Ensure storage policies are permissive enough for the UI to function
drop policy if exists "Public can manage product-images" on storage.objects;
drop policy if exists "Public Storage Full Access" on storage.objects;

create policy "Public Storage Full Access" on storage.objects for all using (
  bucket_id in ('product-images', 'avatars')
) with check (
  bucket_id in ('product-images', 'avatars')
);

-- Trigger function to automatically update the 'updated_at' column
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

-- Apply the trigger to the media_assets table, ensuring it's not duplicated
drop trigger if exists on_media_assets_update on public.media_assets;
create trigger on_media_assets_update
  before update on public.media_assets
  for each row execute procedure public.handle_updated_at();
`;
