
export const MEDIA_COLLECTIONS_SQL = `
-- 9. Media Collections & Product Galleries

-- Create Collections Table
create table if not exists public.media_collections (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Join Table for Many-to-Many relationship
create table if not exists public.collection_media_join (
  collection_id bigint not null references public.media_collections(id) on delete cascade,
  media_id bigint not null references public.media_assets(id) on delete cascade,
  primary key (collection_id, media_id)
);

-- Add collection_id to products table for gallery link
alter table public.products add column if not exists collection_id bigint references public.media_collections(id) on delete set null;

-- Enable RLS
alter table public.media_collections enable row level security;
alter table public.collection_media_join enable row level security;

-- Policies (Permissive for Admin UI)
create policy "Public can manage collections" on public.media_collections for all using (true) with check (true);
create policy "Public can manage collection joins" on public.collection_media_join for all using (true) with check (true);

-- Create a View for easier querying of products with their galleries
-- This view joins products with their assigned collection and aggregates all associated image URLs into an array.
create or replace view public.products_with_gallery as
select
  p.*,
  (
    select array_agg(ma.public_url order by ma.created_at)
    from public.collection_media_join cmj
    join public.media_assets ma on cmj.media_id = ma.id
    where cmj.collection_id = p.collection_id
  ) as gallery_images
from
  public.products p;
`;
