
export const MEDIA_COLLECTIONS_SQL = `
-- 9. Media Collections & Product Galleries

-- Create Collections Table
create table if not exists public.media_collections (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Join Table for Many-to-Many relationship
create table if not exists public.collection_media_join (
  collection_id bigint not null references public.media_collections(id) on delete cascade,
  media_id bigint not null references public.media_assets(id) on delete cascade,
  primary key (collection_id, media_id)
);

-- Enable RLS
alter table public.media_collections enable row level security;
alter table public.collection_media_join enable row level security;

-- Policies (Permissive for Admin UI)
drop policy if exists "Public can manage collections" on public.media_collections;
create policy "Public can manage collections" on public.media_collections for all using (true) with check (true);

drop policy if exists "Public can manage collection joins" on public.collection_media_join;
create policy "Public can manage collection joins" on public.collection_media_join for all using (true) with check (true);
`;