
export const EBOOKS_SETUP_SQL = `
-- 10. E-Books & Library System

-- Add digital fields to products
alter table public.products add column if not exists is_digital boolean default false;
alter table public.products add column if not exists digital_content text; 

-- Create User Library Table
create table if not exists public.user_library (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  last_position integer default 0, -- Percentage scroll (0-100) or page number
  purchase_date timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Ensure a user only has one copy of a book
  unique(user_id, product_id)
);

-- Enable RLS
alter table public.user_library enable row level security;

-- Policies
drop policy if exists "Users can view their own library" on public.user_library;
create policy "Users can view their own library" on public.user_library 
  for select using (auth.uid() = user_id);

-- For demo purposes, we allow public insert (simulated by backend/frontend) 
-- In production, this would be handled by a server-side function triggered by payment
drop policy if exists "Public insert library" on public.user_library;
create policy "Public insert library" on public.user_library 
  for insert with check (true);

drop policy if exists "Users update their progress" on public.user_library;
create policy "Users update their progress" on public.user_library 
  for update using (auth.uid() = user_id);
`;
