
export const ORDER_ARCHIVING_SQL = `
-- 20. Order Archiving System

-- Create Table for Deleted Orders (Audit Log)
create table if not exists public.deleted_orders (
  id bigint generated by default as identity primary key,
  original_id bigint,
  customer_name text,
  customer_email text,
  total_amount numeric,
  items_snapshot jsonb, -- Store the items as a JSON snapshot to avoid FK issues
  deleted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  deleted_by uuid -- Removed strict FK reference to auth.users to support Demo Admin archiving
);

-- FIX 1: Drop strict Foreign Key on deleted_orders if it exists (Crucial for Demo Admin compatibility)
do $$
begin
  if exists (select 1 from information_schema.table_constraints where constraint_name = 'deleted_orders_deleted_by_fkey') then
    alter table public.deleted_orders drop constraint deleted_orders_deleted_by_fkey;
  end if;
end $$;

-- FIX 2: Ensure Order Items are deleted when Order is deleted (Cascade)
-- This prevents "violates foreign key constraint" error when deleting an order that has items.
alter table public.order_items drop constraint if exists order_items_order_id_fkey;
alter table public.order_items add constraint order_items_order_id_fkey
  foreign key (order_id) references public.orders(id) on delete cascade;

-- Enable RLS
alter table public.deleted_orders enable row level security;

-- Policies for Deleted Orders Table
drop policy if exists "Admins can view deleted orders" on public.deleted_orders;
create policy "Admins can view deleted orders" on public.deleted_orders 
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Managers can archive orders" on public.deleted_orders;
create policy "Managers can archive orders" on public.deleted_orders 
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'manager'))
  );

drop policy if exists "Admins can cleanup archives" on public.deleted_orders;
create policy "Admins can cleanup archives" on public.deleted_orders 
  for delete using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Demo Mode Permissive Policy for Deleted Orders
drop policy if exists "Demo Access Deleted Orders" on public.deleted_orders;
create policy "Demo Access Deleted Orders" on public.deleted_orders
  for all using (true) with check (true);

-- FIX 3: Allow Demo Admin (Anon) to DELETE from main orders table
-- The previous policies might have restricted DELETE to authenticated admins only.
drop policy if exists "Managers delete orders" on public.orders;
drop policy if exists "Public delete orders" on public.orders;
create policy "Public delete orders" on public.orders for delete using (true);
`;
