
export const WISHLIST_SETUP_SQL = `
-- 21. Wishlist System

-- Create Wishlist Table
create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate entries for the same user/product pair
  unique(user_id, product_id)
);

-- CRITICAL FIX: Drop the foreign key constraint on user_id.
-- This allows the "Demo Admin" (uuid 0000...0000) to save items to the wishlist.
alter table public.wishlist_items drop constraint if exists wishlist_items_user_id_fkey;

-- Enable RLS
alter table public.wishlist_items enable row level security;

-- Policies

-- 1. Users can view their own wishlist
drop policy if exists "Users view own wishlist" on public.wishlist_items;
create policy "Users view own wishlist" on public.wishlist_items
  for select using (
    auth.uid() = user_id 
    OR 
    user_id = '00000000-0000-0000-0000-000000000000' -- Demo Admin Support
  );

-- 2. Users can add to their own wishlist
drop policy if exists "Users insert own wishlist" on public.wishlist_items;
create policy "Users insert own wishlist" on public.wishlist_items
  for insert with check (
    auth.uid() = user_id 
    OR 
    user_id = '00000000-0000-0000-0000-000000000000'
  );

-- 3. Users can remove from their own wishlist
drop policy if exists "Users delete own wishlist" on public.wishlist_items;
create policy "Users delete own wishlist" on public.wishlist_items
  for delete using (
    auth.uid() = user_id 
    OR 
    user_id = '00000000-0000-0000-0000-000000000000'
  );
`;
